name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-04-01
        override: false
    - name: Packages
      run: sudo apt-get install build-essential yasm
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
